version: "3"
services:
  web:
    build: .
    volumes:
      - "./app:/app"
    ports:
      - "5000:5000"

  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
